#!/bin/bash

opts="-std=c++1z -pedantic-errors -fexceptions"

if [ -z "$1" ]; then
    clang --version
    echo
    echo $opts
    exit 0
fi

out=$2
if [ -z "$out" ]; then
    out=$(basename "$1")
    out=${out%.*}
fi

clang++ $opts -I "$(dirname $0)/../../include" -o "$out" "$1"
