#!/bin/bash

opts="-std=c++1z -pedantic-errors -Wno-attributes"

if [ -z "$1" ]; then
    g++ --version
    echo $opts
    exit 0
fi

out=$2
if [ -z "$out" ]; then
    out=$(basename "$1")
    out=${out%.*}
fi

g++ $opts -I "$(dirname $0)/../../include" -o "$out" "$1"
