#define __cpp_rvalue_references                             __cpp_rvalue_reference


#define __has_feature__cxx_access_control_sfinae            (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 8))
#define __has_feature__cxx_aggregate_nsdmi                  (!!__cpp_aggregate_nsdmi)
#define __has_feature__cxx_alias_templates                  (!!__cpp_alias_templates)
#define __has_feature__cxx_alignas                          (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 8))
#define __has_feature__cxx_alignof                          (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 8))
#define __has_feature__cxx_attributes                       (!!__cpp_attributes)
#define __has_feature__cxx_auto_type                        (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 4))
#define __has_feature__cxx_binary_literals                  (!!__cpp_binary_literals)
#define __has_feature__cxx_constexpr                        (!!__cpp_constexpr)
#define __has_feature__cxx_decltype                         (!!__cpp_decltype)
#define __has_feature__cxx_decltype_auto                    (!!__cpp_decltype_auto)
#define __has_feature__cxx_delegating_constructors          (!!__cpp_delegating_constructors)
#define __has_feature__cxx_exceptions                       (!!__cpp_exceptions)
#define __has_feature__cxx_generic_lambdas                  (!!__cpp_generic_lambdas)
#define __has_feature__cxx_inheriting_constructors          (!!__cpp_inheriting_constructors)
#define __has_feature__cxx_init_captures                    (!!__cpp_init_captures)
#define __has_feature__cxx_lambdas                          (!!__cpp_lambdas)
#define __has_feature__cxx_noexcept                         (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6))
#define __has_feature__cxx_range_for                        (!!__cpp_range_based_for)
#define __has_feature__cxx_raw_string_literals              (!!__cpp_raw_strings)
#define __has_feature__cxx_reference_qualified_functions    (!!__cpp_ref_qualifiers)
#define __has_feature__cxx_return_type_deduction            (!!__cpp_return_type_deduction)
#define __has_feature__cxx_rtti                             (!!__cpp_rtti)
#define __has_feature__cxx_rvalue_references                (!!__cpp_rvalue_references)
#define __has_feature__cxx_static_assert                    (!!__cpp_static_assert)
#define __has_feature__cxx_unicode_literals                 (!!__cpp_unicode_literals)
#define __has_feature__cxx_user_literals                    (!!__cpp_user_defined_literals)
#define __has_feature__cxx_variable_templates               (!!__cpp_variable_templates)
#define __has_feature__cxx_variadic_templates               (!!__cpp_variadic_templates)
